IF
	!Allegiance("BW05GRAC",NEUTRAL)
      See([NEUTRAL.0.0])
      !Dead("BW05GRAC")
      !Class(LastSeenBy(Myself), THIEF)
THEN
	RESPONSE #100
		AttackReEvaluate(LastSeenBy(Myself),30)
END

IF
      !Allegiance("BW05GRAC",NEUTRAL)
      See(NearestEnemyOf(Myself))
      !Dead("BW05GRAC")
THEN
	RESPONSE #100
		AttackReEvaluate(NearestEnemyOf(Myself),30)
END

IF
	Dead("BW05GRAC")
THEN
	RESPONSE #100
		Kill(Myself)
END